### ISSUE TITLE
How to set environment config variables?

### ISSUE THREAD

**Issue by zulhfreelancer** [mattbrictson/capistrano-mb#11]
From the documentation:
> capistrano-mb makes certain assumptions about your Rails app, namely that it uses dotenv to manage Rails secrets via environment variables, and that it runs on top of PostgreSQL and unicorn.

I'm not quite understand it. Can you give some example on how to set config var on production?

What are the steps?

Really appreciate your help / extended documentation about that.

Thanks.

**Comment by mattbrictson** [comment]
In your deploy.rb, list the variables you want to use like this:

```ruby
# This is the default
set :mb_dotenv_keys, %w(rails_secret_key_base postmark_api_key)
```

The next time you deploy, Capistrano will prompt you to enter values for each key. It saves the values in a `.env.production` file on the server.

In your app, you access the values through the environment:

```ruby
# Note the key is upper case
ENV["POSTMARK_API_KEY"]
```

For this to work, your app needs `gem "dotenv-rails", ">= 2.0.0"` in its Gemfile.

**Comment by zulhfreelancer** [comment]
Thanks @mattbrictson, it works!

My steps:

1. I put this inside deploy.rb:
```
set :mb_dotenv_keys, %w(rails_secret_key_base postmark_api_key test_key)
``` 
2. I run `cap production deploy`
3. I answer the prompt for test_key
4. After deploy, I run `cap production rails:console` - I use [this gem](https://github.com/ydkn/capistrano-rails-console)
5. In rails console, I run `ENV['TEST_KEY']` and I can see the key

Another question, how to change the key after first deploy?

Thanks.

**Comment by mattbrictson** [comment]
> how to change the key after first deploy?

You can either:

1. SSH to the server and manually edit the `shared/.env.production` file; or
2. Run `cap production mb:dotenv:replace` to be prompted to enter new values

Note that you will need to restart the app (`deploy:restart`) after changing values.

**Comment by zulhfreelancer** [comment]
It works. Thanks man!
