### ISSUE TITLE
Expecting deployer password to complete the deploy

### ISSUE THREAD

**Issue by mazharoddin** [mattbrictson/capistrano-mb#13]
Hi,
I am using capistrano-mb from long time with out any issue, however due to some issue I had to reformat my mac book, now if try to deploy same app using 'cap production deploy' command, I have prompted to supply deployer password, but I don't remember  if I put any password for deployer user.
```
cat ~/.ssh/id_rsa.pub | ssh root@server 'cat >> ~/.ssh/authorized_keys'
```
I configured password less access using below command, and I am able to access my server without any password for root user.
But when I try to deploy using Capistrano I am getting below error.
```
cap production deploy
00:00 git:wrapper
      01 mkdir -p /tmp
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
deployer@server's password:
```
Please let me know how I can resolve this issue, since I have working app on production server I can't reconfigure the server. Thanks.

**Comment by msimkins** [comment]
You have added your keys for the root user, but not the deployer user

You would need to ssh to the server as root, copy the key to the
deployer user, or of course if you have the root user, you can reset the
deployer password.

**Comment by mazharoddin** [comment]
Hi,
Though I copied keys using root user, it actually gets copied to deployer user .ssh/ directory, because root user doesn't have any .ssh directory.

Yeah I can reset deployer user password, but as far I remember we never set deployer user password while provisioning the app. So don't want to change any existing configuration.

Any way thanks for your suggestions, appreciate it.

**Comment by mazharoddin** [comment]
Yeah, I wrongly copied keys to other directory instead of copying to deployer .ssh directory.
Now its working fine after recopying the .ssh keys to proper deployer user directory.
Thanks all lot.
