### ISSUE TITLE
Unicorn cannot be restarted (requires root) on Ubuntu 16

### ISSUE THREAD

**Issue by tankwanghow** [mattbrictson/capistrano-mb#16]
mb:unicorn:restart problem
ssh to server using **root** and start unicorn is **successful** , but using **deployer** will have the following problem. I think is premission problem please advice.

root
`service unicorn_least_cost_feed restart` - fine

deployer
`service unicorn_least_cost_feed restart` - have folloing error
`Failed to restart unicorn_least_cost_feed.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status unicorn_least_cost_feed.service' for details.`

```
bundle exec cap production mb:unicorn:restart
00:00 mb:unicorn:restart
      01 service unicorn_least_cost_feed restart
      01 Failed to restart unicorn_least_cost_feed.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
      01 See system logs and 'systemctl status unicorn_least_cost_feed.service' for details.
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@106.186.124.38: service unicorn_least_cost_feed restart exit status: 1
service unicorn_least_cost_feed restart stdout: Nothing written
service unicorn_least_cost_feed restart stderr: Failed to restart unicorn_least_cost_feed.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status unicorn_least_cost_feed.service' for details.

SSHKit::Command::Failed: service unicorn_least_cost_feed restart exit status: 1
service unicorn_least_cost_feed restart stdout: Nothing written
service unicorn_least_cost_feed restart stderr: Failed to restart unicorn_least_cost_feed.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status unicorn_least_cost_feed.service' for details.

Tasks: TOP => mb:unicorn:restart
(See full trace by running task with --trace)
zlib(finalizer): the stream was freed prematurely.
```

**Comment by mattbrictson** [comment]
Are you using Ubuntu 16? I believe `root` is required for that version.

I don't have any plans to upgrade capistrano-mb to support Ubuntu 16 at this time. Let me know if you find a workaround!

**Comment by tankwanghow** [comment]
yes i m using ubuntu 16, i will try to find  a workaround. thx

**Comment by mattbrictson** [comment]
I upgraded capistrano-mb to support Ubuntu 16. The solution I came up with for this issue was to add the deployer user to the sudoers list for the `systemctl` commands necessary for starting, stopping, and restarting unicorn. See: ae84a18e
