### ISSUE TITLE
Mutli App Setup

### ISSUE THREAD

**Issue by m43nu** [mattbrictson/capistrano-mb#6]
Hi @mattbrictson 

First of all, this is a really nice setup for a Rails-Environment!
Thank you very much and kudos to your good work!

My question: 
I like to setup a digitalocean droplet with both a staging and a production environment on it.
Is this possible with your gem?

**Comment by mattbrictson** [comment]
@m43nu Generally I do not recommend putting more than one app/environment on a single droplet. You could try setting a different `:application` name in `deploy/staging.rb` vs `deploy/production.rb`. This would allow both environments to be installed side by side under different directories.

However the Nginx config assumes a single application and routes all web traffic to that one application. To serve two apps at once you would have to set up virtual domains somehow, perhaps by manually editing the Nginx config files that capistrano-mb generates.

So, it may be possible, but it would be tricky to get working. I strongly recommend setting up two separate droplets instead.

**Comment by m43nu** [comment]
You're right. I already tried it with the 1-click-image, and it was really tricky...

I thought about it to be more cost-efficient, as the stage-environment won't be running all the time and won't use too much resources. But as the smallest droplet only costs about 5$ a month and the resources are more than sufficient for a simple staging environment, it's ridiculous to not spend this money for a good environment the end-user can benefit fro.

Thanks for your time!
